### ISSUE TITLE
[FIX] approve WearOS new policy in Aug 2023

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/TrafficApplication#10]
## Describe the bug<br/>
WearOS New Guidelines to Apply from August 2023

## TODO<br/>
- [x] Add Splash Screen in Application [#reference](https://developer.android.com/design/ui/wear/guides/behaviors-and-patterns/launch#branded) (WO-V15)
- [x] Add Show time (watch faces) (WO-V12)
- [x] Add User configured font size (WO-V1)
- [x] Add Watch Shapes (WO-V16)
- [x] Update timeout of client (this is server clinet issue)

## Addition Context<br/>
* [Android Developers/Wear App Qulity](https://developer.android.com/docs/quality-guidelines/wear-app-quality)
